baseURL: ''
languageCode: nl
title: Juf Olga
theme: yourfolio
disableKinds: [RSS, taxonomy, taxonomyTerm]
# googleAnalytics: UA-XXXXX-Y

# Menu items
menu:
  main:
  - name: Over
    weight: 1
    url: /about
  - name: Contact
    weight: 2
    url: /contact

# Custom params
params:
  env: development
  logoImage: img/logo.png
  logoImageAlt: Yourfolio Theme brand logo