baseURL: ''
defaultContentLanguage: nl
languageCode: nl
title: Juf Olga
disableKinds: [RSS, taxonomy, taxonomyTerm]
# googleAnalytics: UA-XXXXX-Y

module:
  imports:
    - path: github.com/themefisher/twenty-twenty-hugo

# Menu items
menu:
  main:
    - name: Thuis
      URL: /
      weight: 1
    - name: Over
      URL: about/
      weight: 2
    - name: Video's
      URL: blog/
      weight: 3
    - name: Contact
      URL: contact/
      weight: 4
  desktop:
    - name: Over
      URL: about/
      weight: 1
    - name: Video's
      URL: blog/
      weight: 2
    - name: Contact
      URL: contact/
      weight: 3

paginate: '6'
summaryLength: '10'
disqusShortname: ''
disableLanguages: []

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  category: categories
  tag: tags
  author: author

params:
  description: This is meta description
  author: Juf Olga
  favicon:
    favicon: images/favicon.png
  cookies:
    enable: false
    expire_days: 2
  banner:
    heading: Met plezier leren en lezen voor kleuters
    image: images/2020-landscape-1-2.png
  blog:
    heading: >-
      Video's die leren en lezen leuk maken voor uw kleuter. Gericht op de 
      ontwikkeling van kinderen in groep 1 en 2. Dag en nacht beschikbaar.
  call_to_action:
    enable: true
    title: Neem contact op voor meer informatie.
    content: >-
      Heeft u vragen of suggesties? We horen graag van u! Laat het ons weten
      en we kijken wat we kunnen doen. 
    button_label: Neem contact op
    button_url: contact/
  gallery:
    enable: true
    gallery_item:
      - image: images/2020-square-2.png
      - image: images/2020-square-1.png
  footer:
    title: Over deze website
    content: >-
      Juf Olga heeft meer dan veertig jaar ervaring in ontwikkelingsgericht
      onderwijs voor kleuters. Op deze website deelt zij haar kennis en inzichten. 
    # address: '123 Main Street <br> New York, NY 10001'
    # hours: 'Mondayâ€“Friday: 9:00AMâ€“5:00PM <br> Saturday & Sunday: 11:00AMâ€“3:00PM'
    copyright: >-
      Gebouwd met â˜•ï¸ en ğŸ’œ | [Hugo](https://gohugo.io/) [Twenty Twenty thema](https://themefisher.com/hugo-themes/)
  social:
    # yelp: '#'
    # facebook: '#'
    # twitter: '#'
    # instagram: '#'
    email: 'jufolga@proton.me'
    # linkedin: '#'
